name: build
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master


jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17,16.x,18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm test
      run: |
        npm i
        npm run test:ci
  e2e_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        build: npm run build
        start: npm start
  Deploy-Production:
    needs: [e2e_test, unit_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installf Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
